apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: asb-auth
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "delete"]
- apiGroups: ["authorization.openshift.io"]
  resources: ["subjectrulesreview"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["image.openshift.io", ""]
  attributeRestrictions: null
  resources: ["images"]
  verbs: ["get", "list"]
- apiGroups: ["network.openshift.io", ""]
  attributeRestrictions: null
  resources: ["clusternetworks", "netnamespaces"]
  verbs: ["get"]
- apiGroups: ["network.openshift.io", ""]
  attributeRestrictions: null
  resources: ["netnamespaces"]
  verbs: ["update"]
- apiGroups: ["networking.k8s.io", ""]
  attributeRestrictions: null
  resources: ["networkpolicies"]
  verbs: ["create", "delete"]