# Access credentials of the MySQL ServiceInstance.
# Upon creation, the Service Catalog controller will create a Kubernetes Secret containing connection details and credentials for the Service Instance, which can be mounted into Pods.
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: spring-boot-notes-mysql-binding
spec:
  instanceRef:
    name: mysql
  secretName: spring-boot-notes-mysql-binding